### ISSUE TITLE
Photo Loop Technique

### ISSUE THREAD

**Issue by philsinatra** [erinwiegman/IDM232-002_Project#5]
This does the job but I would like to make it more concise because I feel like I’m repeating myself a lot.

## Functions

Agreed. You worked the `explode` technique out and you have the images in a variable `$infophoto_array`. The first option would be to use functions to avoid having to write the full echo statement out for an image each time. Based on your current code, you could write a single function that accepted one parameter, and returned a string of text that could be echoed to the screen.

```php
// something like this
echo build_me_an_image($infophoto_array[0]);
```

The `build_me_an_image` would setup a string and drop the parameter info in where needed, then return the string to be echoed to the screen. With this technique, you would write the `img` tag structure once, but still use `if` statements to check the array, and you would end up calling the function 1-4 times on the page. It's more concise, but not totally optimized. A valid solution if you decide to go this route.

---

## Grid System

This is **how I would do it** You've already used `explode` to build your array of images. So for this example let's say that is this array:

```php
$infophoto_array = ['one','two','three','four'];
```

Instead of checking for the presence of a value in each of the array slots, you can use the `count` function to write all of the array items, regardless of how many available images there are.

Here's a loop that simply outputs all four images to the screen, each in a `div`. If the array has less (or more) items, the output will reflect whatever the actual _count_ of items is.

```php
<div class="photos">

  <?php
    // You've already used `explode` to build your array of images.
    $infophoto_array = ['one','two','three','four'];

    // Instead of checking for the presence of a value in each of the array slots,
    // you can use the `count` function to write all of the array items, regardless
    // of how many available images there are.
    for ($i=0; $i < count($infophoto_array); $i++) {
      echo "<div class=\"photo_{$i}\">";
      echo $infophoto_array[$i];
      echo "</div>";
    }
  ?>

</div>
```

Now we have a container (`photos`) and inside we have some number of additional `div` containers (each with a class that reflects which slot in the array the image is coming from - `photo_0`, `photo_1` etc).

Here's the magic - [CSS Grid](https://css-tricks.com/snippets/css/complete-guide-grid/)

```css
  .photos {
    display: grid;
    grid-template-columns: 1fr 1fr;
    grid-column-gap: 2rem;
    grid-row-gap: 2rem;
  }

  .photo_0, .photo_3 {
    grid-column-start: 1;
    grid-column-end: span 2;
  }
```

### Breakdown

```css
  .photos {
    /* Tell the browser to display the parent container as a grid */
    display: grid;
    /* Define the grid's columns. 1fr = one fraction of the available space.
    So 1fr 1fr means there will be two columns, each taking up one fraction
    of the available width. */
    grid-template-columns: 1fr 1fr;
    /* The space between columns. Think of it like a margin. */
    grid-column-gap: 2rem;
    /* The space between rows. Again, think of it like a margin. */
    grid-row-gap: 2rem;
  }
```

So we have a grid that is row after row of two equal width columns. The first child `div` will go in the first slot (top left). The next `div` child will go in the next slot (top right). Then the third `div` will go into the second row, left column, and so on. No matter how many `div` children you put into the `photos` container, they will keep stacking side by side in a two column grid.

You want the first and fourth items to take up the full width instead of only one of the `fr`.

```css
  .photo_0, .photo_3 {
    /* The first and fourth items from the array (remember arrays start at 0)
   will both start at the first column of the grid, but will `span` both of the 
    `1fr` columns. */
    grid-column-start: 1;
    grid-column-end: span 2;
  }
```

![grid](https://user-images.githubusercontent.com/1465808/27134092-77b400da-50e2-11e7-9d7e-8b2bf0f6c704.png)

With this type of setup you can have any number of images. The first and fourth items will always be larger. If there were more than four, the fifth and beyond would go back to the two column layout. Don't want the space between the images? Just edit/remove the `gap` properties in the CSS.

Attached zip is the full sample code for you to use as a reference, if you decide to implement this technique as your solution.

[weigman.zip](https://github.com/erinwiegman/IDM232-002_Project/files/1074676/weigman.zip)

### Developing Tip

Use Firefox for working with CSS Grid. It has a built in function for previewing the grid and the gaps. When you open the DevTools and select the grid item, you can toggle the grid outlines on/off using the icon in the properties inspector.

![devtools](https://user-images.githubusercontent.com/1465808/27134304-2d0b4a9c-50e3-11e7-9ac9-563f3e441220.png)
